import { desc } from "drizzle-orm";
import { redirect } from "next/navigation";
import { currentUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { notificationEvents } from "@/lib/db/schema";
import { getOptionalConfig } from "@/lib/env";
import { AppShell } from "@/components/app-shell";
import { CustodyStrip, Metric } from "@/components/ui";
export default async function Diagnostics() { const user = await currentUser(); if (!user) redirect("/login"); if (user.role !== "admin") redirect("/upload"); const [events, config] = await Promise.all([db().select().from(notificationEvents).orderBy(desc(notificationEvents.createdAt)).limit(20), Promise.resolve(getOptionalConfig())]); return <AppShell user={user}><header className="page-header"><div><CustodyStrip route="DIAG">CONFIG:MASKED ▦ EVENTS:LAST20 ▦ SECRET-VALUES:NEVER</CustodyStrip><span className="eyebrow">SAFE DIAGNOSTICS</span><h1>Configuration health</h1><p>Secrets remain hidden. This view exposes only operational readiness.</p></div></header><section className="metric-grid"><Metric label="Database" value={config.database ? "Configured" : "Missing"} /><Metric label="Authentication" value={config.auth ? "Configured" : "Missing"} /><Metric label="Private storage" value={config.storage ? "Configured" : "Missing"} /><Metric label="Email" value={config.email ? "Configured" : "Not configured"} /></section><section className="admin-panel material-surface"><div className="panel-head"><div><span className="eyebrow">NOTIFICATION EVENTS</span><h2>Recent delivery notices</h2></div></div>{events.length ? <ul className="diagnostic-list">{events.map((event) => <li key={event.id}><b>{event.status}</b><span>{event.error || "No error detail recorded."}</span><time>{new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(event.createdAt)}</time></li>)}</ul> : <p className="empty-inline">No notification failures recorded.</p>}</section></AppShell>; }
