"use client";
import { FormEvent, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { useRouter } from "next/navigation";
import { RippleButton } from "@/components/ui";

export default function LoginPage() {
  const router = useRouter(); const reduce = useReducedMotion(); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [remember, setRemember] = useState(true); const [showPassword, setShowPassword] = useState(false); const [caps, setCaps] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (!username.trim() || !password) { setError("Enter both your username and password."); return; } setLoading(true); const res = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password, remember }) }); const data = await res.json(); setLoading(false); if (!res.ok) { setError(data.error); return; } router.push(data.role === "admin" ? "/admin" : "/upload"); router.refresh(); }
  return <main className="login-page"><div className="login-light light-blue" /><div className="login-light light-teal" /><motion.section className="login-intro" initial={reduce ? false : { opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ type: "spring", stiffness: 130, damping: 20 }}><div className="brand-lockup"><b>MM</b><span>mmoptibuilds<small>ENGINEERED PERFORMANCE</small></span></div><div className="intro-copy"><span className="eyebrow">SECURE ASSET TRANSFER · 01</span><h1>Built for the files that build the work.</h1><p>A direct, resilient transfer workspace for high-resolution assets, source files, and complete project folders.</p></div><div className="signal-panel"><span>TRANSFER STATUS</span><b><i />Drive ready</b><em>Encrypted session · structured delivery</em></div></motion.section><motion.section className="login-card material-glass" initial={reduce ? false : { opacity: 0, scale: 0.96, x: 32 }} animate={{ opacity: 1, scale: 1, x: 0 }} transition={{ type: "spring", stiffness: 125, damping: 19, delay: reduce ? 0 : 0.1 }}><div className="card-heading"><span className="eyebrow">CLIENT ACCESS</span><h2>Upload ready.</h2><p>Sign in with the credentials sent by mmoptibuilds.</p></div><form onSubmit={submit} noValidate><div className="floating-field"><input id="username" value={username} onChange={(e) => setUsername(e.target.value)} autoComplete="username" required placeholder=" " /><label htmlFor="username">Username</label></div><div className="floating-field"><input id="password" type={showPassword ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} onKeyUp={(e) => setCaps(e.getModifierState("CapsLock"))} onKeyDown={(e) => setCaps(e.getModifierState("CapsLock"))} autoComplete="current-password" required placeholder=" " /><label htmlFor="password">Password</label><button className="password-toggle" type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(!showPassword)}>{showPassword ? "HIDE" : "SHOW"}</button></div><AnimatePresence>{caps && <motion.p className="field-note warning" initial={{ opacity: 0, y: -4 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>Caps Lock is on.</motion.p>}</AnimatePresence><label className="check"><input type="checkbox" checked={remember} onChange={(e) => setRemember(e.target.checked)} /><span />Remember this device for 30 days</label><AnimatePresence>{error && <motion.p role="alert" className="form-error" initial={{ opacity: 0, y: -6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>{error}</motion.p>}</AnimatePresence><RippleButton className="button-primary login-submit" type="submit" disabled={loading}>{loading ? "Checking secure access…" : "Enter workspace"}<b>→</b></RippleButton></form><small className="login-footer">No public registration. Need access? Contact mmoptibuilds.</small></motion.section></main>;
}
