"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import { Icon, type IconName, RippleButton } from "@/components/ui";
export function AppShell({ children, user }: { children: React.ReactNode; user: { username: string; role: string } }) {
  const path = usePathname(); const router = useRouter(); const [loggingOut, setLoggingOut] = useState(false);
  async function logout() { setLoggingOut(true); try { await fetch("/api/auth/logout", { method: "POST" }); } finally { router.push("/login"); router.refresh(); } }
  const links: Array<{ label: string; href: string; icon: IconName }> = user.role === "admin" ? [{ label: "Overview", href: "/admin", icon: "activity" }, { label: "Upload batches", href: "/admin/uploads", icon: "upload" }, { label: "Users", href: "/admin/users", icon: "users" }, { label: "Diagnostics", href: "/admin/diagnostics", icon: "shield" }, { label: "Client portal", href: "/upload", icon: "arrow-right" }] : [{ label: "Upload", href: "/upload", icon: "upload" }, { label: "History", href: "/history", icon: "activity" }];
  const isActive = (href: string) => path === href || path.startsWith(`${href}/`);
  return <div className="app-frame"><a className="skip-link" href="#main-content">Skip to content</a><aside className="side-nav"><Link className="brand-lockup" aria-label="mmoptibuilds home" href={user.role === "admin" ? "/admin" : "/upload"}><b>MM</b><span>mmoptibuilds<small>ENGINEERED PERFORMANCE</small></span></Link><nav aria-label="Primary navigation">{links.map(({ label, href, icon }) => <Link key={href} className={isActive(href) ? "active" : ""} aria-current={isActive(href) ? "page" : undefined} href={href}><Icon name={icon} size={16} /><span>{label}</span></Link>)}</nav><RippleButton type="button" aria-label="Log out" title="Log out" aria-busy={loggingOut} className="button-quiet mobile-logout" disabled={loggingOut} onClick={logout}><Icon name="log-out" size={17} /></RippleButton><div className="account"><span className="avatar" aria-hidden="true">{user.username.slice(0, 1).toUpperCase()}</span><div><b>{user.username}</b><small>{user.role}</small></div><RippleButton type="button" aria-label="Log out" title="Log out" aria-busy={loggingOut} className="button-quiet" disabled={loggingOut} onClick={logout}><Icon name="log-out" size={17} /></RippleButton></div></aside><main className="app-content" id="main-content">{children}</main></div>;
}
